### PR TITLE
Geocode and use the location of empty surveys	

### LINKED ISSUE #56: Empty surveys should center on the geocoded survey location.

### PR DESCRIPTION
**Pull request by hampelm**
It makes sense to focus empty surveys on their specified location (rather than defaulting to San Francisco in all cases).  Fixes #56

### CODE REVIEW

**Comment by hampelm** [comment]
We could also geocode the survey location on save and store it in the API. That would require adding another survey fields and tests, but would be a bit faster long-term. 

We're using bing for geocoding and it's not likely we'll hit any limits, so caching isn't important there.

**Comment by prashtx** [comment]
If the geocoding service fails to return coordinates for the survey location, will we end up using (0,0) and zoom 15 for the map?

**Comment by hampelm** [comment]
Yes, it'll stay at the default 0,0 location if things fail. We can use SF if that's more realistic.

**Comment by prashtx** [comment]
Let's use SF. 0,0 far enough from major land mass that it's not a super graceful degradation.

**Comment by hampelm** [comment]
@prashtx used SF in 0da255f

**Pull request merged**
