### PR TITLE
Trim whitespace from questions and answers

### PR DESCRIPTION
**Pull request by hampelm**
Uses the new String functions in lodash 3.

Should prevent ugly questions and answers like `---Question-requires-a-lot-of-spaces--`

### CODE REVIEW

**Comment by prashtx** [comment]
Do we need to adjust anything to account for breaking changes between lodash 2.4 and 3.0?
https://github.com/lodash/lodash/wiki/Changelog#compatibility-warnings

I'm not sure if we still do any immediate template rendering (vs. separate compilation + render), but that's a possible issue. That and maybe `_.flatten` are the things that jump out as possibilities.

**Comment by hampelm** [comment]
I searched `src` for `_.flatten` and didn't find anything. I also looked at a couple other things under the compatibility warnings and didn't see any issues in our code. 

I also tested filtering, checking a response, editing a response, editing the form, and changing the settings and things seemed to work fine.

**Comment by prashtx** [comment]
I think this is case of 2.4-only `_.template` usage: https://github.com/LocalData/localdata-dashboard/blob/28e3d4d493a238ec76e8c5eb989045bd581bd959/src/js/views/users.js#L63

Not sure what the least tedious way is to identify other instances. We mostly avoid it already because of potential performance penalties.

**Comment by hampelm** [comment]
@prashtx I think I've got all the instances. I did a fairly broad regex search for `_.template(`s with a comma). I then did a bunch of manual tests of different features.

**Pull request merged**
